# Generated by Django 2.0.6 on 2018-06-02 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('battles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tweet',
            name='typos',
            field=models.IntegerField(default=0),
        ),
    ]
