# Generated by Django 2.0.6 on 2018-06-02 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('battles', '0002_tweet_typos'),
    ]

    operations = [
        migrations.AddField(
            model_name='battle',
            name='name',
            field=models.CharField(default='default', max_length=200),
            preserve_default=False,
        ),
    ]
